// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WorkHive.Data.Models;

public partial class Amenity
{
    public int Id { get; set; }

    public string Name { get; set; }

    public decimal? Price { get; set; }

    public int? Quantity { get; set; }

    public string ImgUrl { get; set; }

    public string Description { get; set; }

    public string Category { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int BookingAmenityId { get; set; }

    public virtual BookingAmenity BookingAmenity { get; set; }
}