// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WorkHive.Data.Models;

public partial class Beverage
{
    public int Id { get; set; }

    public string Name { get; set; }

    public decimal? Price { get; set; }

    public string ImgUrl { get; set; }

    public string Description { get; set; }

    public string Category { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int OwnerId { get; set; }

    public virtual ICollection<BookingBeverage> BookingBeverages { get; set; } = new List<BookingBeverage>();

    public virtual WorkspaceOwner Owner { get; set; }
}