// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WorkHive.Data.Models;

public partial class BookingAmenity
{
    public int Id { get; set; }

    public string Status { get; set; }

    public int BookingWorkspaceId { get; set; }

    public virtual ICollection<Amenity> Amenities { get; set; } = new List<Amenity>();

    public virtual BookingWorkspace BookingWorkspace { get; set; }
}