// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WorkHive.Data.Models;

public partial class Booking
{
    public int Id { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public decimal? Price { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int UserId { get; set; }

    public int PaymentId { get; set; }

    public int WorkspaceId { get; set; }

    public int? IsReview { get; set; }

    public int? PromotionId { get; set; }

    public virtual ICollection<BookingAmenity> BookingAmenities { get; set; } = new List<BookingAmenity>();

    public virtual ICollection<BookingBeverage> BookingBeverages { get; set; } = new List<BookingBeverage>();

    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    public virtual PaymentMethod Payment { get; set; }

    public virtual Promotion Promotion { get; set; }

    public virtual ICollection<Rating> Ratings { get; set; } = new List<Rating>();

    public virtual User User { get; set; }

    public virtual Workspace Workspace { get; set; }

    public virtual ICollection<WorkspaceTime> WorkspaceTimes { get; set; } = new List<WorkspaceTime>();
}