// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WorkHive.Data.Models;

public partial class BookingAmenity
{
    public int Id { get; set; }

    public string Status { get; set; }

    public int? Quantity { get; set; }

    public int BookingId { get; set; }

    public int AmenityId { get; set; }

    public virtual Amenity Amenity { get; set; }

    public virtual Booking Booking { get; set; }
}