// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WorkHive.Data.Models;

public partial class BookingBeverage
{
    public int Id { get; set; }

    public string Status { get; set; }

    public int? Quantity { get; set; }

    public int BookingWorkspaceId { get; set; }

    public int BeverageId { get; set; }

    public virtual Beverage Beverage { get; set; }

    public virtual Booking BookingWorkspace { get; set; }
}