// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WorkHive.Data.Models;

public partial class CustomerWallet
{
    public int Id { get; set; }

    public string Status { get; set; }

    public int WalletId { get; set; }

    public int UserId { get; set; }

    public virtual User User { get; set; }

    public virtual ICollection<UserTransactionHistory> UserTransactionHistories { get; set; } = new List<UserTransactionHistory>();

    public virtual Wallet Wallet { get; set; }
}