// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WorkHive.Data.Models;

public partial class Feedback
{
    public int Id { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public int UserId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int BookingId { get; set; }

    public string Title { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual ICollection<ImageFeedback> ImageFeedbacks { get; set; } = new List<ImageFeedback>();

    public virtual ICollection<OwnerResponseFeedback> OwnerResponseFeedbacks { get; set; } = new List<OwnerResponseFeedback>();

    public virtual User User { get; set; }
}