// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WorkHive.Data.Models;

public partial class Feedback
{
    public int Id { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public int UserId { get; set; }

    public int OwnerId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? BookingId { get; set; }

    public virtual ICollection<ImageFeedback> ImageFeedbacks { get; set; } = new List<ImageFeedback>();

    public virtual Booking Owner { get; set; }

    public virtual WorkspaceOwner OwnerNavigation { get; set; }

    public virtual ICollection<OwnerResponeFeedback> OwnerResponeFeedbacks { get; set; } = new List<OwnerResponeFeedback>();

    public virtual User User { get; set; }
}