// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WorkHive.Data.Models;

public partial class ImageResponseFeedback
{
    public int Id { get; set; }

    public string Status { get; set; }

    public int ResponseFeedbackId { get; set; }

    public int ImageId { get; set; }

    public virtual Image Image { get; set; }

    public virtual OwnerResponeFeedback ResponseFeedback { get; set; }
}