// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WorkHive.Data.Models;

public partial class Image
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string ImgUrl { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<ImageFeedback> ImageFeedbacks { get; set; } = new List<ImageFeedback>();

    public virtual ICollection<WorkspaceImage> WorkspaceImages { get; set; } = new List<WorkspaceImage>();

    public virtual ICollection<WorkspaceRatingImage> WorkspaceRatingImages { get; set; } = new List<WorkspaceRatingImage>();
}