// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WorkHive.Data.Models;

public partial class ImageFeedback
{
    public int Id { get; set; }

    public string Status { get; set; }

    public int FeedbackId { get; set; }

    public int ImageId { get; set; }

    public virtual Feedback Feedback { get; set; }

    public virtual Image Image { get; set; }
}