// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WorkHive.Data.Models;

public partial class Owner
{
    public int Id { get; set; }

    public string BusinessName { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public string GoogleMapUrl { get; set; }

    public string Description { get; set; }

    public string SocialUrl { get; set; }

    public string License { get; set; }

    public string OwnerName { get; set; }

    public string OwnerIdentityCard { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Amenity> Amenities { get; set; } = new List<Amenity>();

    public virtual ICollection<Beverage> Beverages { get; set; } = new List<Beverage>();

    public virtual ICollection<OwnerWallet> OwnerWallets { get; set; } = new List<OwnerWallet>();

    public virtual ICollection<Promotion> Promotions { get; set; } = new List<Promotion>();

    public virtual ICollection<Workspace> Workspaces { get; set; } = new List<Workspace>();
}