// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WorkHive.Data.Models;

public partial class OwnerTransactionHistory
{
    public int Id { get; set; }

    public string Status { get; set; }

    public int TransactionHistoryId { get; set; }

    public int OwnerWalletId { get; set; }

    public virtual OwnerWallet OwnerWallet { get; set; }

    public virtual TransactionHistory TransactionHistory { get; set; }
}