// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WorkHive.Data.Models;

public partial class OwnerResponseFeedback
{
    public int Id { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public int OwnerId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int FeedbackId { get; set; }

    public string Title { get; set; }

    public virtual Feedback Feedback { get; set; }

    public virtual ICollection<ImageResponseFeedback> ImageResponseFeedbacks { get; set; } = new List<ImageResponseFeedback>();

    public virtual WorkspaceOwner Owner { get; set; }
}