// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WorkHive.Data.Models;

public partial class OwnerWallet
{
    public int Id { get; set; }

    public string Status { get; set; }

    public int WalletId { get; set; }

    public int OwnerId { get; set; }

    public virtual Owner Owner { get; set; }

    public virtual ICollection<OwnerTransactionHistory> OwnerTransactionHistories { get; set; } = new List<OwnerTransactionHistory>();

    public virtual Wallet Wallet { get; set; }
}