// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WorkHive.Data.Models;

public partial class OwnerPasswordResetToken
{
    public int Id { get; set; }

    public string Token { get; set; }

    public DateTime? ExpiredAt { get; set; }

    public int? IsUsed { get; set; }

    public int OwnerId { get; set; }

    public virtual WorkspaceOwner Owner { get; set; }
}