// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WorkHive.Data.Models;

public partial class Payment
{
    public int Id { get; set; }

    public string PaymentMethod { get; set; }

    public string Status { get; set; }

    public virtual ICollection<BookingWorkspace> BookingWorkspaces { get; set; } = new List<BookingWorkspace>();
}