// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WorkHive.Data.Models;

public partial class Promotion
{
    public int Id { get; set; }

    public string Code { get; set; }

    public int? Discount { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string Status { get; set; }

    public int WorkspaceId { get; set; }

    public int OwnerId { get; set; }

    public virtual WorkspaceOwner Owner { get; set; }

    public virtual Workspace Workspace { get; set; }
}