// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WorkHive.Data.Models;

public partial class Rating
{
    public int Id { get; set; }

    public byte? Rate { get; set; }

    public string Comment { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int UserId { get; set; }

    public virtual User User { get; set; }

    public virtual ICollection<WorkspaceRating> WorkspaceRatings { get; set; } = new List<WorkspaceRating>();
}