// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WorkHive.Data.Models;

public partial class UserPasswordResetToken
{
    public int Id { get; set; }

    public string Token { get; set; }

    public DateTime? ExpriedAt { get; set; }

    public int? IsUsed { get; set; }

    public int UserId { get; set; }

    public virtual User User { get; set; }
}