// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WorkHive.Data.Models;

public partial class Wallet
{
    public int Id { get; set; }

    public decimal? Balance { get; set; }

    public string Status { get; set; }

    public virtual ICollection<CustomerWallet> CustomerWallets { get; set; } = new List<CustomerWallet>();

    public virtual ICollection<OwnerWallet> OwnerWallets { get; set; } = new List<OwnerWallet>();
}