// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WorkHive.Data.Models;

public partial class WorkspaceRating
{
    public int Id { get; set; }

    public string Status { get; set; }

    public int RatingId { get; set; }

    public int WorkspaceId { get; set; }

    public virtual Rating Rating { get; set; }

    public virtual Workspace Workspace { get; set; }

    public virtual ICollection<WorkspaceRatingImage> WorkspaceRatingImages { get; set; } = new List<WorkspaceRatingImage>();
}