// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WorkHive.Data.Models;

public partial class Workspace
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int? Capacity { get; set; }

    public string Category { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int? CleanTime { get; set; }

    public int? Area { get; set; }

    public int OwnerId { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<FacilityWorkspace> FacilityWorkspaces { get; set; } = new List<FacilityWorkspace>();

    public virtual Owner Owner { get; set; }

    public virtual ICollection<WorkspaceImage> WorkspaceImages { get; set; } = new List<WorkspaceImage>();

    public virtual ICollection<WorkspacePolicy> WorkspacePolicies { get; set; } = new List<WorkspacePolicy>();

    public virtual ICollection<WorkspacePrice> WorkspacePrices { get; set; } = new List<WorkspacePrice>();

    public virtual ICollection<WorkspaceRating> WorkspaceRatings { get; set; } = new List<WorkspaceRating>();
}