// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WorkHive.Data.Models;

public partial class WorkspaceFacility
{
    public int Id { get; set; }

    public int FacilityId { get; set; }

    public int WorkspaceId { get; set; }

    public virtual Facility Facility { get; set; }

    public virtual Workspace Workspace { get; set; }
}