// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WorkHive.Data.Models;

public partial class WorkspaceImage
{
    public int Id { get; set; }

    public DateTime? Status { get; set; }

    public int WorkspaceId { get; set; }

    public int ImageId { get; set; }

    public virtual Image Image { get; set; }

    public virtual Workspace Workspace { get; set; }
}